### PR TITLE
Allow for custom thumbnails to only need a width or height and not both

### PR DESCRIPTION
**Pull request by mburst**
Validated by https://github.com/Imgur/mandible/blob/master/server/server_test.go#L553

Can add more tests if desired

### CODE REVIEW

**Comment by lospro7** [comment]
@mburst what's the reason for the change?

**Comment by lospro7** [comment]
The condition and the PR title confused me a little, so only fail if both the `width` AND the `height` are invalid, correct?

**Comment by mburst** [comment]
The goal of this PR is to make it so that we can take an image say 1080x720 and scale based on a single dimension (width or height). After the last PR both were accidentally required. This is fixing a bug in the current implementation.

**Comment by jacobgreenleaf** [comment]
:+1:

**Comment by briankassouf** [comment]
:+1:

**Pull request merged**
