### PR TITLE
Use GraphicsMagick

### PR DESCRIPTION
**Pull request by abvarun226**
* Swap to GraphicsMagick

@pastudan

### CODE REVIEW

**Comment by briankassouf** [comment]
I think this will break webp conversions as well as OCR functionality

**Comment by abvarun226** [comment]
Webp is fixed but OCR functionality is till broken.

**Comment by abvarun226** [comment]
We are not using the OCR functionality as per Dan and the Devops team. Can we ignore/kill it?

**Comment by abvarun226** [comment]
Looks like only DuelOCR test is failing.

**Comment by briankassouf** [comment]
Seems okay to me! I can look at fixing the OCR test in another PR

**Comment by abvarun226** [comment]
Thank you! I'll merge this PR for now. I can help with fixing DuelOCR later.

**Pull request merged**
