### PR TITLE
Use GO15VENDOREXPERIMENT; Move vendored code to vendor/ directory; Us…

### PR DESCRIPTION
**Pull request by jacobgreenleaf**
…e godep in build

### CODE REVIEW

**Comment by briankassouf** [comment]
:+1:

**Comment by mburst** [comment]
Looks legit :m: :a: :x:

**Comment by mburst** [comment]
Looks like the build is still failing https://travis-ci.org/Imgur/mandible/builds/104752284

**Comment by mburst** [comment]
:m: :a: :x:

**Pull request merged**
